// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/appointment/appointment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppointmentStreamResponse_EventType int32

const (
	AppointmentStreamResponse_CREATED AppointmentStreamResponse_EventType = 0
	AppointmentStreamResponse_UPDATED AppointmentStreamResponse_EventType = 1
	AppointmentStreamResponse_DELETED AppointmentStreamResponse_EventType = 2
)

// Enum value maps for AppointmentStreamResponse_EventType.
var (
	AppointmentStreamResponse_EventType_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DELETED",
	}
	AppointmentStreamResponse_EventType_value = map[string]int32{
		"CREATED": 0,
		"UPDATED": 1,
		"DELETED": 2,
	}
)

func (x AppointmentStreamResponse_EventType) Enum() *AppointmentStreamResponse_EventType {
	p := new(AppointmentStreamResponse_EventType)
	*p = x
	return p
}

func (x AppointmentStreamResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentStreamResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_appointment_appointment_proto_enumTypes[0].Descriptor()
}

func (AppointmentStreamResponse_EventType) Type() protoreflect.EnumType {
	return &file_proto_appointment_appointment_proto_enumTypes[0]
}

func (x AppointmentStreamResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentStreamResponse_EventType.Descriptor instead.
func (AppointmentStreamResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{7, 0}
}

// Appointment message definition
type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Appointment) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Appointment) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Appointment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Appointment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request messages
type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAppointmentRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateAppointmentRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentRequest) Reset() {
	*x = UpdateAppointmentRequest{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentRequest) ProtoMessage() {}

func (x *UpdateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAppointmentRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateAppointmentRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type DeleteAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentRequest) Reset() {
	*x = DeleteAppointmentRequest{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentRequest) ProtoMessage() {}

func (x *DeleteAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *ListAppointmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAppointmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAppointmentsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListAppointmentsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ListAppointmentsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *ListAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

func (x *ListAppointmentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAppointmentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAppointmentsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AppointmentStreamResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	EventType     AppointmentStreamResponse_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=appointment.AppointmentStreamResponse_EventType" json:"event_type,omitempty"`
	Appointment   *Appointment                        `protobuf:"bytes,2,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentStreamResponse) Reset() {
	*x = AppointmentStreamResponse{}
	mi := &file_proto_appointment_appointment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentStreamResponse) ProtoMessage() {}

func (x *AppointmentStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_appointment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentStreamResponse.ProtoReflect.Descriptor instead.
func (*AppointmentStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_appointment_proto_rawDescGZIP(), []int{7}
}

func (x *AppointmentStreamResponse) GetEventType() AppointmentStreamResponse_EventType {
	if x != nil {
		return x.EventType
	}
	return AppointmentStreamResponse_CREATED
}

func (x *AppointmentStreamResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

var File_proto_appointment_appointment_proto protoreflect.FileDescriptor

const file_proto_appointment_appointment_proto_rawDesc = "" +
	"\n" +
	"#proto/appointment/appointment.proto\x12\vappointment\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9b\x02\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa2\x01\n" +
	"\x18CreateAppointmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"'\n" +
	"\x15GetAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x01\n" +
	"\x18UpdateAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"*\n" +
	"\x18DeleteAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcd\x01\n" +
	"\x17ListAppointmentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x98\x01\n" +
	"\x18ListAppointmentsResponse\x12<\n" +
	"\fappointments\x18\x01 \x03(\v2\x18.appointment.AppointmentR\fappointments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xdc\x01\n" +
	"\x19AppointmentStreamResponse\x12O\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e20.appointment.AppointmentStreamResponse.EventTypeR\teventType\x12:\n" +
	"\vappointment\x18\x02 \x01(\v2\x18.appointment.AppointmentR\vappointment\"2\n" +
	"\tEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x022\x9d\x04\n" +
	"\x12AppointmentService\x12T\n" +
	"\x11CreateAppointment\x12%.appointment.CreateAppointmentRequest\x1a\x18.appointment.Appointment\x12N\n" +
	"\x0eGetAppointment\x12\".appointment.GetAppointmentRequest\x1a\x18.appointment.Appointment\x12T\n" +
	"\x11UpdateAppointment\x12%.appointment.UpdateAppointmentRequest\x1a\x18.appointment.Appointment\x12R\n" +
	"\x11DeleteAppointment\x12%.appointment.DeleteAppointmentRequest\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\x10ListAppointments\x12$.appointment.ListAppointmentsRequest\x1a%.appointment.ListAppointmentsResponse\x12V\n" +
	"\x12StreamAppointments\x12\x16.google.protobuf.Empty\x1a&.appointment.AppointmentStreamResponse0\x01B8Z6github.com/pasDamola/schedule-management-system/pkg/pbb\x06proto3"

var (
	file_proto_appointment_appointment_proto_rawDescOnce sync.Once
	file_proto_appointment_appointment_proto_rawDescData []byte
)

func file_proto_appointment_appointment_proto_rawDescGZIP() []byte {
	file_proto_appointment_appointment_proto_rawDescOnce.Do(func() {
		file_proto_appointment_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appointment_appointment_proto_rawDesc), len(file_proto_appointment_appointment_proto_rawDesc)))
	})
	return file_proto_appointment_appointment_proto_rawDescData
}

var file_proto_appointment_appointment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_appointment_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_appointment_appointment_proto_goTypes = []any{
	(AppointmentStreamResponse_EventType)(0), // 0: appointment.AppointmentStreamResponse.EventType
	(*Appointment)(nil),                      // 1: appointment.Appointment
	(*CreateAppointmentRequest)(nil),         // 2: appointment.CreateAppointmentRequest
	(*GetAppointmentRequest)(nil),            // 3: appointment.GetAppointmentRequest
	(*UpdateAppointmentRequest)(nil),         // 4: appointment.UpdateAppointmentRequest
	(*DeleteAppointmentRequest)(nil),         // 5: appointment.DeleteAppointmentRequest
	(*ListAppointmentsRequest)(nil),          // 6: appointment.ListAppointmentsRequest
	(*ListAppointmentsResponse)(nil),         // 7: appointment.ListAppointmentsResponse
	(*AppointmentStreamResponse)(nil),        // 8: appointment.AppointmentStreamResponse
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 10: google.protobuf.Empty
}
var file_proto_appointment_appointment_proto_depIdxs = []int32{
	9,  // 0: appointment.Appointment.start_time:type_name -> google.protobuf.Timestamp
	9,  // 1: appointment.Appointment.end_time:type_name -> google.protobuf.Timestamp
	9,  // 2: appointment.Appointment.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: appointment.Appointment.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: appointment.CreateAppointmentRequest.start_time:type_name -> google.protobuf.Timestamp
	9,  // 5: appointment.CreateAppointmentRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 6: appointment.UpdateAppointmentRequest.start_time:type_name -> google.protobuf.Timestamp
	9,  // 7: appointment.UpdateAppointmentRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 8: appointment.ListAppointmentsRequest.start_date:type_name -> google.protobuf.Timestamp
	9,  // 9: appointment.ListAppointmentsRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 10: appointment.ListAppointmentsResponse.appointments:type_name -> appointment.Appointment
	0,  // 11: appointment.AppointmentStreamResponse.event_type:type_name -> appointment.AppointmentStreamResponse.EventType
	1,  // 12: appointment.AppointmentStreamResponse.appointment:type_name -> appointment.Appointment
	2,  // 13: appointment.AppointmentService.CreateAppointment:input_type -> appointment.CreateAppointmentRequest
	3,  // 14: appointment.AppointmentService.GetAppointment:input_type -> appointment.GetAppointmentRequest
	4,  // 15: appointment.AppointmentService.UpdateAppointment:input_type -> appointment.UpdateAppointmentRequest
	5,  // 16: appointment.AppointmentService.DeleteAppointment:input_type -> appointment.DeleteAppointmentRequest
	6,  // 17: appointment.AppointmentService.ListAppointments:input_type -> appointment.ListAppointmentsRequest
	10, // 18: appointment.AppointmentService.StreamAppointments:input_type -> google.protobuf.Empty
	1,  // 19: appointment.AppointmentService.CreateAppointment:output_type -> appointment.Appointment
	1,  // 20: appointment.AppointmentService.GetAppointment:output_type -> appointment.Appointment
	1,  // 21: appointment.AppointmentService.UpdateAppointment:output_type -> appointment.Appointment
	10, // 22: appointment.AppointmentService.DeleteAppointment:output_type -> google.protobuf.Empty
	7,  // 23: appointment.AppointmentService.ListAppointments:output_type -> appointment.ListAppointmentsResponse
	8,  // 24: appointment.AppointmentService.StreamAppointments:output_type -> appointment.AppointmentStreamResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_appointment_appointment_proto_init() }
func file_proto_appointment_appointment_proto_init() {
	if File_proto_appointment_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appointment_appointment_proto_rawDesc), len(file_proto_appointment_appointment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appointment_appointment_proto_goTypes,
		DependencyIndexes: file_proto_appointment_appointment_proto_depIdxs,
		EnumInfos:         file_proto_appointment_appointment_proto_enumTypes,
		MessageInfos:      file_proto_appointment_appointment_proto_msgTypes,
	}.Build()
	File_proto_appointment_appointment_proto = out.File
	file_proto_appointment_appointment_proto_goTypes = nil
	file_proto_appointment_appointment_proto_depIdxs = nil
}
